language: rust
cache: cargo
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

rust:
  - nightly

before_script:
  - git clone https://github.com/apache/thrift.git
  - cd thrift && git checkout -b 0.11.0 origin/0.11.0 && ./bootstrap.sh
  - ./configure --enable-libs=no
  - make && sudo make install
  - cd $TRAVIS_BUILD_DIR/src/parquet_thrift && thrift --gen rs parquet.thrift
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
  - cargo install cargo-travis --force && export PATH=$HOME/.cargo/bin:$PATH

script:
  - cd $TRAVIS_BUILD_DIR
  - travis-cargo build
  - travis-cargo test

after_success:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo bench;
    fi
  - cargo coveralls --verbose --exclude-pattern '/parquet-rs/src/parquet_thrift,/parquet-rs/src/bin'

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""

dist: trusty

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake
